export interface Product {
  id: number
  name: string
  price: number
  images: string[]
  stock: number
  isNew: boolean
  category: string
}

export const categoryProducts: { [key: string]: Product[] } = {
  rings: [
    {
      id: 101,
      name: "خاتم ذهبي كلاسيكي",
      price: 250000,
      images: ["/gold-ring-classic.jpg", "/gold-ring-classic.jpg", "/gold-ring-classic.jpg"],
      stock: 15,
      isNew: true,
      category: "rings",
    },
    {
      id: 102,
      name: "خاتم فضي بالأحجار الكريمة",
      price: 180000,
      images: ["/silver-ring-gemstones.jpg", "/silver-ring-gemstones.jpg", "/silver-ring-gemstones.jpg"],
      stock: 8,
      isNew: false,
      category: "rings",
    },
    {
      id: 103,
      name: "خاتم الخطوبة الماسي",
      price: 450000,
      images: ["/diamond-engagement-ring.jpg", "/diamond-engagement-ring.jpg", "/diamond-engagement-ring.jpg"],
      stock: 3,
      isNew: true,
      category: "rings",
    },
    {
      id: 104,
      name: "خاتم ذهب أبيض عصري",
      price: 320000,
      images: ["/white-gold-modern-ring.jpg", "/white-gold-modern-ring.jpg", "/white-gold-modern-ring.jpg"],
      stock: 12,
      isNew: false,
      category: "rings",
    },
    {
      id: 105,
      name: "خاتم فضي بسيط",
      price: 95000,
      images: ["/simple-silver-ring.jpg", "/simple-silver-ring.jpg", "/simple-silver-ring.jpg"],
      stock: 25,
      isNew: false,
      category: "rings",
    },
    {
      id: 106,
      name: "خاتم ذهبي بالزمرد",
      price: 380000,
      images: ["/gold-emerald-ring.jpg", "/gold-emerald-ring.jpg", "/gold-emerald-ring.jpg"],
      stock: 6,
      isNew: true,
      category: "rings",
    },
    {
      id: 107,
      name: "خاتم التيتانيوم الرياضي",
      price: 150000,
      images: ["/titanium-sport-ring.jpg", "/titanium-sport-ring.jpg", "/titanium-sport-ring.jpg"],
      stock: 18,
      isNew: false,
      category: "rings",
    },
    {
      id: 108,
      name: "خاتم الياقوت الأزرق",
      price: 420000,
      images: ["/blue-sapphire-ring.jpg", "/blue-sapphire-ring.jpg", "/blue-sapphire-ring.jpg"],
      stock: 4,
      isNew: true,
      category: "rings",
    },
    {
      id: 109,
      name: "خاتم فضي منقوش",
      price: 125000,
      images: ["/engraved-silver-ring.jpg", "/engraved-silver-ring.jpg", "/engraved-silver-ring.jpg"],
      stock: 14,
      isNew: false,
      category: "rings",
    },
    {
      id: 110,
      name: "خاتم ذهبي بالؤلؤ",
      price: 280000,
      images: ["/gold-pearl-ring.jpg", "/gold-pearl-ring.jpg", "/gold-pearl-ring.jpg"],
      stock: 9,
      isNew: false,
      category: "rings",
    },
    {
      id: 111,
      name: "خاتم الزفاف المطابق",
      price: 350000,
      images: ["/matching-wedding-ring.jpg", "/matching-wedding-ring.jpg", "/matching-wedding-ring.jpg"],
      stock: 7,
      isNew: true,
      category: "rings",
    },
    {
      id: 112,
      name: "خاتم فضي بالعقيق",
      price: 165000,
      images: ["/silver-agate-ring.jpg", "/silver-agate-ring.jpg", "/silver-agate-ring.jpg"],
      stock: 11,
      isNew: false,
      category: "rings",
    },
  ],

  earrings: [
    {
      id: 201,
      name: "أقراط ذهبية دائرية",
      price: 220000,
      images: ["/gold-hoop-earrings.png", "/gold-hoop-earrings.png", "/gold-hoop-earrings.png"],
      stock: 16,
      isNew: true,
      category: "earrings",
    },
    {
      id: 202,
      name: "أقراط فضية بالكريستال",
      price: 145000,
      images: ["/silver-crystal-earrings.jpg", "/silver-crystal-earrings.jpg", "/silver-crystal-earrings.jpg"],
      stock: 12,
      isNew: false,
      category: "earrings",
    },
    {
      id: 203,
      name: "أقراط الماس متدلية",
      price: 520000,
      images: ["/diamond-drop-earrings.jpg", "/diamond-drop-earrings.jpg", "/diamond-drop-earrings.jpg"],
      stock: 5,
      isNew: true,
      category: "earrings",
    },
    {
      id: 204,
      name: "أقراط ذهب أبيض صغيرة",
      price: 180000,
      images: ["/small-white-gold-earrings.jpg", "/small-white-gold-earrings.jpg", "/small-white-gold-earrings.jpg"],
      stock: 20,
      isNew: false,
      category: "earrings",
    },
    {
      id: 205,
      name: "أقراط فضية طويلة",
      price: 95000,
      images: ["/long-silver-earrings.png", "/long-silver-earrings.png", "/long-silver-earrings.png"],
      stock: 18,
      isNew: false,
      category: "earrings",
    },
    {
      id: 206,
      name: "أقراط ذهبية بالزمرد",
      price: 380000,
      images: ["/gold-emerald-earrings.jpg", "/gold-emerald-earrings.jpg", "/gold-emerald-earrings.jpg"],
      stock: 8,
      isNew: true,
      category: "earrings",
    },
    {
      id: 207,
      name: "أقراط اللؤلؤ الكلاسيكية",
      price: 250000,
      images: ["/classic-pearl-earrings.jpg", "/classic-pearl-earrings.jpg", "/classic-pearl-earrings.jpg"],
      stock: 14,
      isNew: false,
      category: "earrings",
    },
    {
      id: 208,
      name: "أقراط الياقوت الأحمر",
      price: 450000,
      images: [
        "/placeholder.svg?height=300&width=300",
        "/placeholder.svg?height=300&width=300",
        "/placeholder.svg?height=300&width=300",
      ],
      stock: 6,
      isNew: true,
      category: "earrings",
    },
    {
      id: 209,
      name: "أقراط فضية هندسية",
      price: 125000,
      images: [
        "/placeholder.svg?height=300&width=300",
        "/placeholder.svg?height=300&width=300",
        "/placeholder.svg?height=300&width=300",
      ],
      stock: 22,
      isNew: false,
      category: "earrings",
    },
    {
      id: 210,
      name: "أقراط ذهبية بالتوباز",
      price: 320000,
      images: [
        "/placeholder.svg?height=300&width=300",
        "/placeholder.svg?height=300&width=300",
        "/placeholder.svg?height=300&width=300",
      ],
      stock: 10,
      isNew: false,
      category: "earrings",
    },
    {
      id: 211,
      name: "أقراط الشاندلير الفاخرة",
      price: 480000,
      images: [
        "/placeholder.svg?height=300&width=300",
        "/placeholder.svg?height=300&width=300",
        "/placeholder.svg?height=300&width=300",
      ],
      stock: 4,
      isNew: true,
      category: "earrings",
    },
    {
      id: 212,
      name: "أقراط فضية بالعقيق الأسود",
      price: 165000,
      images: [
        "/placeholder.svg?height=300&width=300",
        "/placeholder.svg?height=300&width=300",
        "/placeholder.svg?height=300&width=300",
      ],
      stock: 13,
      isNew: false,
      category: "earrings",
    },
  ],

  bracelets: [
    {
      id: 301,
      name: "سوار ذهبي سلسلة",
      price: 280000,
      images: [
        "/placeholder.svg?height=300&width=300",
        "/placeholder.svg?height=300&width=300",
        "/placeholder.svg?height=300&width=300",
      ],
      stock: 14,
      isNew: true,
      category: "bracelets",
    },
    {
      id: 302,
      name: "سوار فضي بالأحجار",
      price: 165000,
      images: [
        "/placeholder.svg?height=300&width=300",
        "/placeholder.svg?height=300&width=300",
        "/placeholder.svg?height=300&width=300",
      ],
      stock: 18,
      isNew: false,
      category: "bracelets",
    },
    {
      id: 303,
      name: "سوار التنس الماسي",
      price: 650000,
      images: [
        "/placeholder.svg?height=300&width=300",
        "/placeholder.svg?height=300&width=300",
        "/placeholder.svg?height=300&width=300",
      ],
      stock: 3,
      isNew: true,
      category: "bracelets",
    },
    {
      id: 304,
      name: "سوار ذهب أبيض عريض",
      price: 420000,
      images: [
        "/placeholder.svg?height=300&width=300",
        "/placeholder.svg?height=300&width=300",
        "/placeholder.svg?height=300&width=300",
      ],
      stock: 9,
      isNew: false,
      category: "bracelets",
    },
    {
      id: 305,
      name: "سوار فضي رفيع",
      price: 85000,
      images: [
        "/placeholder.svg?height=300&width=300",
        "/placeholder.svg?height=300&width=300",
        "/placeholder.svg?height=300&width=300",
      ],
      stock: 25,
      isNew: false,
      category: "bracelets",
    },
    {
      id: 306,
      name: "سوار ذهبي بالزمرد",
      price: 480000,
      images: [
        "/placeholder.svg?height=300&width=300",
        "/placeholder.svg?height=300&width=300",
        "/placeholder.svg?height=300&width=300",
      ],
      stock: 6,
      isNew: true,
      category: "bracelets",
    },
    {
      id: 307,
      name: "سوار اللؤلؤ الطبيعي",
      price: 320000,
      images: [
        "/placeholder.svg?height=300&width=300",
        "/placeholder.svg?height=300&width=300",
        "/placeholder.svg?height=300&width=300",
      ],
      stock: 11,
      isNew: false,
      category: "bracelets",
    },
    {
      id: 308,
      name: "سوار الياقوت الأزرق",
      price: 550000,
      images: [
        "/placeholder.svg?height=300&width=300",
        "/placeholder.svg?height=300&width=300",
        "/placeholder.svg?height=300&width=300",
      ],
      stock: 4,
      isNew: true,
      category: "bracelets",
    },
    {
      id: 309,
      name: "سوار فضي منقوش",
      price: 145000,
      images: [
        "/placeholder.svg?height=300&width=300",
        "/placeholder.svg?height=300&width=300",
        "/placeholder.svg?height=300&width=300",
      ],
      stock: 16,
      isNew: false,
      category: "bracelets",
    },
    {
      id: 310,
      name: "سوار ذهبي بالتوباز",
      price: 380000,
      images: [
        "/placeholder.svg?height=300&width=300",
        "/placeholder.svg?height=300&width=300",
        "/placeholder.svg?height=300&width=300",
      ],
      stock: 8,
      isNew: false,
      category: "bracelets",
    },
    {
      id: 311,
      name: "سوار الشارم الفضي",
      price: 195000,
      images: [
        "/placeholder.svg?height=300&width=300",
        "/placeholder.svg?height=300&width=300",
        "/placeholder.svg?height=300&width=300",
      ],
      stock: 12,
      isNew: true,
      category: "bracelets",
    },
    {
      id: 312,
      name: "سوار فضي بالعقيق",
      price: 175000,
      images: [
        "/placeholder.svg?height=300&width=300",
        "/placeholder.svg?height=300&width=300",
        "/placeholder.svg?height=300&width=300",
      ],
      stock: 15,
      isNew: false,
      category: "bracelets",
    },
  ],

  necklaces: [
    {
      id: 401,
      name: "سلسلة ذهبية كلاسيكية",
      price: 350000,
      images: [
        "/placeholder.svg?height=300&width=300",
        "/placeholder.svg?height=300&width=300",
        "/placeholder.svg?height=300&width=300",
      ],
      stock: 12,
      isNew: true,
      category: "necklaces",
    },
    {
      id: 402,
      name: "سلسلة فضية بالقلادة",
      price: 185000,
      images: [
        "/placeholder.svg?height=300&width=300",
        "/placeholder.svg?height=300&width=300",
        "/placeholder.svg?height=300&width=300",
      ],
      stock: 16,
      isNew: false,
      category: "necklaces",
    },
    {
      id: 403,
      name: "سلسلة الماس الفاخرة",
      price: 750000,
      images: [
        "/placeholder.svg?height=300&width=300",
        "/placeholder.svg?height=300&width=300",
        "/placeholder.svg?height=300&width=300",
      ],
      stock: 2,
      isNew: true,
      category: "necklaces",
    },
    {
      id: 404,
      name: "سلسلة ذهب أبيض طويلة",
      price: 420000,
      images: [
        "/placeholder.svg?height=300&width=300",
        "/placeholder.svg?height=300&width=300",
        "/placeholder.svg?height=300&width=300",
      ],
      stock: 8,
      isNew: false,
      category: "necklaces",
    },
    {
      id: 405,
      name: "سلسلة فضية بسيطة",
      price: 95000,
      images: [
        "/placeholder.svg?height=300&width=300",
        "/placeholder.svg?height=300&width=300",
        "/placeholder.svg?height=300&width=300",
      ],
      stock: 22,
      isNew: false,
      category: "necklaces",
    },
    {
      id: 406,
      name: "سلسلة ذهبية بالزمرد",
      price: 520000,
      images: [
        "/placeholder.svg?height=300&width=300",
        "/placeholder.svg?height=300&width=300",
        "/placeholder.svg?height=300&width=300",
      ],
      stock: 5,
      isNew: true,
      category: "necklaces",
    },
    {
      id: 407,
      name: "سلسلة اللؤلؤ الطبيعي",
      price: 380000,
      images: [
        "/placeholder.svg?height=300&width=300",
        "/placeholder.svg?height=300&width=300",
        "/placeholder.svg?height=300&width=300",
      ],
      stock: 10,
      isNew: false,
      category: "necklaces",
    },
    {
      id: 408,
      name: "سلسلة الياقوت الأحمر",
      price: 650000,
      images: [
        "/placeholder.svg?height=300&width=300",
        "/placeholder.svg?height=300&width=300",
        "/placeholder.svg?height=300&width=300",
      ],
      stock: 3,
      isNew: true,
      category: "necklaces",
    },
    {
      id: 409,
      name: "سلسلة فضية متعددة الطبقات",
      price: 165000,
      images: [
        "/placeholder.svg?height=300&width=300",
        "/placeholder.svg?height=300&width=300",
        "/placeholder.svg?height=300&width=300",
      ],
      stock: 14,
      isNew: false,
      category: "necklaces",
    },
    {
      id: 410,
      name: "سلسلة ذهبية بالتوباز",
      price: 450000,
      images: [
        "/placeholder.svg?height=300&width=300",
        "/placeholder.svg?height=300&width=300",
        "/placeholder.svg?height=300&width=300",
      ],
      stock: 7,
      isNew: false,
      category: "necklaces",
    },
    {
      id: 411,
      name: "سلسلة الشوكر العصرية",
      price: 280000,
      images: [
        "/placeholder.svg?height=300&width=300",
        "/placeholder.svg?height=300&width=300",
        "/placeholder.svg?height=300&width=300",
      ],
      stock: 11,
      isNew: true,
      category: "necklaces",
    },
    {
      id: 412,
      name: "سلسلة فضية بالعقيق",
      price: 195000,
      images: [
        "/placeholder.svg?height=300&width=300",
        "/placeholder.svg?height=300&width=300",
        "/placeholder.svg?height=300&width=300",
      ],
      stock: 13,
      isNew: false,
      category: "necklaces",
    },
  ],

  watches: [
    {
      id: 501,
      name: "ساعة ذهبية كلاسيكية",
      price: 850000,
      images: [
        "/placeholder.svg?height=300&width=300",
        "/placeholder.svg?height=300&width=300",
        "/placeholder.svg?height=300&width=300",
      ],
      stock: 8,
      isNew: true,
      category: "watches",
    },
    {
      id: 502,
      name: "ساعة فضية رياضية",
      price: 420000,
      images: [
        "/placeholder.svg?height=300&width=300",
        "/placeholder.svg?height=300&width=300",
        "/placeholder.svg?height=300&width=300",
      ],
      stock: 15,
      isNew: false,
      category: "watches",
    },
    {
      id: 503,
      name: "ساعة الماس الفاخرة",
      price: 1200000,
      images: [
        "/placeholder.svg?height=300&width=300",
        "/placeholder.svg?height=300&width=300",
        "/placeholder.svg?height=300&width=300",
      ],
      stock: 2,
      isNew: true,
      category: "watches",
    },
    {
      id: 504,
      name: "ساعة ذهب أبيض أنيقة",
      price: 680000,
      images: [
        "/placeholder.svg?height=300&width=300",
        "/placeholder.svg?height=300&width=300",
        "/placeholder.svg?height=300&width=300",
      ],
      stock: 6,
      isNew: false,
      category: "watches",
    },
    {
      id: 505,
      name: "ساعة فضية بسيطة",
      price: 280000,
      images: [
        "/placeholder.svg?height=300&width=300",
        "/placeholder.svg?height=300&width=300",
        "/placeholder.svg?height=300&width=300",
      ],
      stock: 18,
      isNew: false,
      category: "watches",
    },
    {
      id: 506,
      name: "ساعة ذهبية بالزمرد",
      price: 950000,
      images: [
        "/placeholder.svg?height=300&width=300",
        "/placeholder.svg?height=300&width=300",
        "/placeholder.svg?height=300&width=300",
      ],
      stock: 4,
      isNew: true,
      category: "watches",
    },
    {
      id: 507,
      name: "ساعة اللؤلؤ النسائية",
      price: 520000,
      images: [
        "/placeholder.svg?height=300&width=300",
        "/placeholder.svg?height=300&width=300",
        "/placeholder.svg?height=300&width=300",
      ],
      stock: 10,
      isNew: false,
      category: "watches",
    },
    {
      id: 508,
      name: "ساعة الياقوت الأزرق",
      price: 1100000,
      images: [
        "/placeholder.svg?height=300&width=300",
        "/placeholder.svg?height=300&width=300",
        "/placeholder.svg?height=300&width=300",
      ],
      stock: 3,
      isNew: true,
      category: "watches",
    },
    {
      id: 509,
      name: "ساعة فضية عتيقة",
      price: 380000,
      images: [
        "/placeholder.svg?height=300&width=300",
        "/placeholder.svg?height=300&width=300",
        "/placeholder.svg?height=300&width=300",
      ],
      stock: 12,
      isNew: false,
      category: "watches",
    },
    {
      id: 510,
      name: "ساعة ذهبية بالتوباز",
      price: 750000,
      images: [
        "/placeholder.svg?height=300&width=300",
        "/placeholder.svg?height=300&width=300",
        "/placeholder.svg?height=300&width=300",
      ],
      stock: 7,
      isNew: false,
      category: "watches",
    },
    {
      id: 511,
      name: "ساعة ذكية فاخرة",
      price: 650000,
      images: [
        "/placeholder.svg?height=300&width=300",
        "/placeholder.svg?height=300&width=300",
        "/placeholder.svg?height=300&width=300",
      ],
      stock: 9,
      isNew: true,
      category: "watches",
    },
    {
      id: 512,
      name: "ساعة فضية بالعقيق",
      price: 420000,
      images: [
        "/placeholder.svg?height=300&width=300",
        "/placeholder.svg?height=300&width=300",
        "/placeholder.svg?height=300&width=300",
      ],
      stock: 11,
      isNew: false,
      category: "watches",
    },
  ],

  glasses: [
    {
      id: 601,
      name: "نظارة شمسية ذهبية",
      price: 320000,
      images: [
        "/placeholder.svg?height=300&width=300",
        "/placeholder.svg?height=300&width=300",
        "/placeholder.svg?height=300&width=300",
      ],
      stock: 14,
      isNew: true,
      category: "glasses",
    },
    {
      id: 602,
      name: "نظارة فضية كلاسيكية",
      price: 185000,
      images: [
        "/placeholder.svg?height=300&width=300",
        "/placeholder.svg?height=300&width=300",
        "/placeholder.svg?height=300&width=300",
      ],
      stock: 18,
      isNew: false,
      category: "glasses",
    },
    {
      id: 603,
      name: "نظارة الماس الفاخرة",
      price: 650000,
      images: [
        "/placeholder.svg?height=300&width=300",
        "/placeholder.svg?height=300&width=300",
        "/placeholder.svg?height=300&width=300",
      ],
      stock: 3,
      isNew: true,
      category: "glasses",
    },
    {
      id: 604,
      name: "نظارة ذهب أبيض عصرية",
      price: 280000,
      images: [
        "/placeholder.svg?height=300&width=300",
        "/placeholder.svg?height=300&width=300",
        "/placeholder.svg?height=300&width=300",
      ],
      stock: 12,
      isNew: false,
      category: "glasses",
    },
    {
      id: 605,
      name: "نظارة فضية بسيطة",
      price: 125000,
      images: [
        "/placeholder.svg?height=300&width=300",
        "/placeholder.svg?height=300&width=300",
        "/placeholder.svg?height=300&width=300",
      ],
      stock: 25,
      isNew: false,
      category: "glasses",
    },
    {
      id: 606,
      name: "نظارة ذهبية بالزمرد",
      price: 480000,
      images: [
        "/placeholder.svg?height=300&width=300",
        "/placeholder.svg?height=300&width=300",
        "/placeholder.svg?height=300&width=300",
      ],
      stock: 6,
      isNew: true,
      category: "glasses",
    },
    {
      id: 607,
      name: "نظارة اللؤلؤ الأنيقة",
      price: 350000,
      images: [
        "/placeholder.svg?height=300&width=300",
        "/placeholder.svg?height=300&width=300",
        "/placeholder.svg?height=300&width=300",
      ],
      stock: 10,
      isNew: false,
      category: "glasses",
    },
    {
      id: 608,
      name: "نظارة الياقوت الأزرق",
      price: 580000,
      images: [
        "/placeholder.svg?height=300&width=300",
        "/placeholder.svg?height=300&width=300",
        "/placeholder.svg?height=300&width=300",
      ],
      stock: 4,
      isNew: true,
      category: "glasses",
    },
    {
      id: 609,
      name: "نظارة فضية مربعة",
      price: 165000,
      images: [
        "/placeholder.svg?height=300&width=300",
        "/placeholder.svg?height=300&width=300",
        "/placeholder.svg?height=300&width=300",
      ],
      stock: 16,
      isNew: false,
      category: "glasses",
    },
    {
      id: 610,
      name: "نظارة ذهبية بالتوباز",
      price: 420000,
      images: [
        "/placeholder.svg?height=300&width=300",
        "/placeholder.svg?height=300&width=300",
        "/placeholder.svg?height=300&width=300",
      ],
      stock: 8,
      isNew: false,
      category: "glasses",
    },
    {
      id: 611,
      name: "نظارة الطيار الكلاسيكية",
      price: 250000,
      images: [
        "/placeholder.svg?height=300&width=300",
        "/placeholder.svg?height=300&width=300",
        "/placeholder.svg?height=300&width=300",
      ],
      stock: 13,
      isNew: true,
      category: "glasses",
    },
    {
      id: 612,
      name: "نظارة فضية بالعقيق",
      price: 195000,
      images: [
        "/placeholder.svg?height=300&width=300",
        "/placeholder.svg?height=300&width=300",
        "/placeholder.svg?height=300&width=300",
      ],
      stock: 15,
      isNew: false,
      category: "glasses",
    },
  ],
}

// Function to get products by category
export function getProductsByCategory(category: string): Product[] {
  return categoryProducts[category] || []
}

// Function to get product count by category
export function getProductCountByCategory(category: string): number {
  return categoryProducts[category]?.length || 0
}
